name: filcnaplo_wearos
description: "Nem hivatalos e-napló alkalmazás az e-Kréta rendszerhez"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wear: ^1.1.0
  filcnaplo_wearable_ui:
    path: "../filcnaplo_wearable_ui"
  filcnaplo_kreta_api:
    path: "../filcnaplo_kreta_api/"
  filcnaplo:
    path: "../filcnaplo/"
  
  i18n_extension: ^4.1.0
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0
  intl: ^0.17.0
  provider: ^5.0.0
  http: ^0.13.3
  uuid: ^3.0.4
  html: ^0.15.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  permission_handler: ^9.2.0
  material_color_utilities: ^0.1.3
  share_plus: ^4.0.4
  connectivity_plus: ^2.0.2
  implicitly_animated_reorderable_list: ^0.4.2
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/ic_launcher.png
    - assets/icons/ic_splash.png

  fonts:
    - family: FilcIcons
      fonts:
        - asset: "../filcnaplo/assets/fonts/FilcIcons.ttf"
    - family: Montserrat
      fonts:
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Black.ttf"
          weight: 900
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-BlackItalic.ttf"
          weight: 900
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-ExtraBold.ttf"
          weight: 800
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf"
          weight: 800
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Bold.ttf"
          weight: 700
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-BoldItalic.ttf"
          weight: 700
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-SemiBold.ttf"
          weight: 600
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf"
          weight: 600
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Medium.ttf"
          weight: 500
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-MediumItalic.ttf"
          weight: 500
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Regular.ttf"
          weight: 400
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Italic.ttf"
          weight: 400
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Light.ttf"
          weight: 300
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-LightItalic.ttf"
          weight: 300
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-ExtraLight.ttf"
          weight: 200
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf"
          weight: 200
          style: italic
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-Thin.ttf"
          weight: 100
        - asset: "../filcnaplo/assets/fonts/Montserrat/Montserrat-ThinItalic.ttf"
          weight: 100
          style: italic

    - family: SpaceMono
      fonts:
        - asset: "../filcnaplo/assets/fonts/SpaceMono/SpaceMono-Regular.ttf"
        - asset: "../filcnaplo/assets/fonts/SpaceMono/SpaceMono-Bold.ttf"
          weight: 700
        - asset: "../filcnaplo/assets/fonts/SpaceMono/SpaceMono-Italic.ttf"
          style: italic
        - asset: "../filcnaplo/assets/fonts/SpaceMono/SpaceMono-BoldItalic.ttf"
          weight: 700
          style: italic